export const error_email_required = "Email is required."
export const error_email_invalid = "Please enter a valid email."
export const error_passowrd_required = "Password is required."
export const error_password_max_length = "Password must be at least 6 characters long."
export const mismatch_password = "Mismatch password. Please check it."
export const error_url_required = "URL is required."

export const error_first_name_required = "First Name is required."
export const error_duplicate_first_name = "First Name is duplicated other name"
export const error_last_name_required = "Last Name is required."
export const error_duplicate_last_name = "Last Name is duplicated other name"
export const error_middle_name_required = "Middle Name is required."
export const error_duplicate_middle_name = "Middle Name is duplicated other name"
export const error_phone_number_required = "Phone Number is required."
export const error_phone_number_invalid = "Please enter a valid phone number."
export const error_birthday_required = "Your Birthday is required."

export const error_post_code_required = "Post Code is required."
export const error_address_required = "Address is required."
export const error_houseno_required = "House No is required."
export const error_building_name_required = "Building Name is required."
export const error_address_info_required = "Address Info is required."
export const error_street_name_required = "Street Name is required."
export const error_city_required = "City is required."
export const error_country_required = "Country is required."
export const error_county_required = "County is required."
export const error_nation_required = "Nationallity is required."
export const network_error = "Unable to process details, please connect Naxetra Support Team"
export const success_email_otp = "Email OTP has been sent again"
export const failed_email_otp ="Email OTP hasn't been sent again"

export const success_mobile_otp = "Mobile OTP has been sent again"
export const failed_mobile_otp ="Mobile OTP hasn't been sent again"
export const error_post_code_message = "You have to input post code."

export const error_find_not_user = "Can't find user information. Try again."
export const error_onfido_verify = "Verification failed. Please try again."

//not error message

export const success_add_beneficiary = "Your beneficiary has been added successfully. You can now transfer funds with ease."
export const error_new_password = "New Password must be at least 6 characters long."